### ISSUE TITLE
look into implementing a batching scheduler

### ISSUE THREAD

**Issue by lwahlmeier** [threadly/threadly#104]
The goal would be to try and batch jobs together at the same time.  It should allow for periodic tasks to have a min, and max delay then figure out how best to run everything to wake up cpus as little as possible.

**Comment by jentfoo** [comment]
I thought a bit more about this.  I think the NoThreadScheduler can provide what we were looking at here, assuming you still don't want to run scheduled tasks early just to include them in a batch.  And also assuming a single thread of execution is enough.

Either way I am thinking about closing this, since it has been open so long.

**Comment by jentfoo** [comment]
No one complained, so I am going to go ahead and close this.  I do think that NoThreadScheduler could provide a trivial way to implement this.
