### ISSUE TITLE
Look at possible efficency improvements by forcing cpu affinity

### ISSUE THREAD

**Issue by jentfoo** [threadly/threadly#152]
This came from a discussion on reddit.  The idea would be if we can group similar tasks on to the same CPU core, we will more likely have better cache hit rates.  It seems for things like the KeyDistributedExceutor this could be very valuable.  But even in the PriorityScheduler maybe we could look at runnable class to pick which core it should run on.  Of course we would have to ensure we don't force too much on a core, and end up becoming single threaded (since all the work submitted is of the same type).

We would need some sort of JNI sadly to force the cpu core.

I am not sure how this would look exactly, or what costs we will end up having to do this logic, or how large the benefits will be.  So this may not be a good idea at all, but I do figure its at least worth attempting to find out.

**Comment by lwahlmeier** [comment]
I am not sure how suited java would be for this, at least in the since that the scheduler could every figure this out on its own.  At best all you could do is look for identical runnables and then try to put them on the same core and thread, but there is a lot of line cutting involved with it and the JNI call to set threads affinity would be hard to do and keep it from getting out of hand.

I think the best way to do this in the java world might be to have a "Set Core Scheduler" Which has a thread or 2 set on each cpu core.  Then when someone calls something to be executed they can set which core it should run on.  That should help with the extra jni over head since basically you would only have it on creating of the pool, but there are still alot of technical issues (line cutting of jobs, etc) that would still need to be figured out.

All that said, I dont think its really worth it from adding JNI, I also feel like modern kernel schedulers will do this, to a point, provided you keep things on the same thread, which means just using the keyDistributer might be enough to start seeing this.  Obviously if you over thread the cpu cores it wont be able to at a certain point.  Anyway its something to think about.

**Comment by jentfoo** [comment]
Yea, I had some of the same thoughts.  Here is a bit more details about how it might work in this theoretical scheduler:

* When thread worker is started, if the thread count is < the core count, it's affinity is set to the next core which does not have an affinity already set to it.  If there has been one thread per core already assigned, then threads are started with NO affinity set.  Basically giving us two classes of workers.

* At task submission time we figure out what the ideal core for this task to run on would be.

* When a task is ready to run, we check what it's ideal affinity is.  If that thread is available, we provide it to that thread.  If it's not available, we provide it to a thread with no affinity set.  We attempt that class of threads first so that threads with affinity will be available for tasks which request them.  If there are no available threads without affinity set, then we randomly select an idle thread with affinity set (even thought that affinity does not match our ideal affinity).

So this puts the load of setting the affinity on thread startup time, and the load of determining the affinity of task submission time.  So hopefully that will not have too much impact.

What concerns me most is:

* Now our thread storage model becomes more complicated.  Threads need to do more logic on how they are returned to the pool, and consumed from the pool.  In addition there is more logic around how we find an available thread (vs an ArrayDeque pop which is super cheap).

* What hidden dragons may exist within the scheduler when affinity is force

**Comment by jentfoo** [comment]
The part that sucks the most is the need for JNI, and thus OS specific distributions of threadly.

**Comment by lwahlmeier** [comment]
The more I think about it the more I see it as very very application specific.  I dont think there would ever be a good way to detect if something should run on the same core automatically, even if we just put the same runnable object on the same core we have no idea if/how it might have been wrapped or if there is a benefit.  

All that being said if we did an implementation that allowed threads to bind to cpu you would almost have to have a different .execute/submit/schedule allowing them to set the core affinity for the job.

If we go down this route I think the JNI/OS affinity stuff should live in another lib that threadly depends on, kind of like how SWT would work, we use a common api to set affinity in threadly and they include the OS specific library for it.

**Comment by jentfoo** [comment]
Yea, I agree.  I do think there is a potential for some decent improvements given the right use case.  I agree it makes sense to make a new scheduler, with a new API for it.

That said the more I got into this I realized it probably is not a rode I want to go down right now.  I think it would be better to focus on Ambush and the heap dump analyzer.

**Comment by jentfoo** [comment]
I am going to close this for now.  There may be something of value here, but I want to keep native code of this project (so it would be a new project if we do want to go down this road).

Like luke said, the KeyDistributedExecutor kind of does this by trying to keep like tasks on the same thread, it's questionable if there is much to gain above that.
