### ISSUE TITLE
Possible 5.0.0 versioning scheme change

### ISSUE THREAD

**Issue by jentfoo** [threadly/threadly#211]
Filing an issue as mostly a place to have an open discussion.  @lwahlmeier and @blendmaster I would love your opinions on this.

First the background (which you may know).  As threadly has matured the semantic versioning has become less beneficial in my opinion.  Specifically I find us waiting to release new features until a "critical mass" has occurred so that we don't increment that middle number like crazy.  With threadly now being very stable, and with a great set of automated testing, I want to move closer and closer to CD.

Because of that, I have been trying to consider if `5.0.0` should mark a change.  Here is some potential ideas.  I am curious if any of these seem to have merit, or might give you an idea for something I have not considered.

* We could just let the middle number increment like crazy.  I am not really in favor of this because I feel like what's the point of having `.0` at the end of almost all releases (we already do, but it would get even worse).

* We could stick with three digits, but change how we increment them.  This idea is more open.  Somehow the middle digit must indicate a evolution of stability, but I am unsure how we define this (after a month without changes we increment?)

* We could go to just two digits, only incrementing the major version for API breaking changes, but otherwise bug fixes and feature expansions would have a version increment in the same way.

* We could go down to two digits, but with a tick/tock style of version scheme.  This is basically the versioning pre `1.0.0`.  In this we would go to `5.0` but we would only put in risky features on odd versions, and try to keep even versions to a minimal level of change.  We moved away from this because in some ways this has the same issues that we have with not wanting to increment the middle number for minor feature expansions.  Except in this one we would hit the situation "we have an even release coming up, but this feature is significant and thus must wait".

Thoughts?  Ultimately we need to choose something that will inspire confidence and communicate stability in the clearest way possible.  Semantic may be the continual choice just because it's common and understood, but now is at least the time to be thinking about it.

**Comment by blendmaster** [comment]
This looks like a fun bikeshed.

>I find us waiting to release new features until a "critical mass" has occurred so that we don't increment that middle number like crazy.

What's bad about incrementing the middle number like crazy? Is it just annoying to procedurally do the version bump commit, push a release to maven, all that jazz? Is there a "marketing" component, where it seems less attractive to have a bunch of tiny releases on the release page with one-item changelogs? I think exploring that bad feeling about incrementing will be helpful.

One "law of versioning thermodynamics" here is that the faster you want to release new stable features to general availability, the more unique versions you must have.

In a not entirely perverse sense, a bugfix is just another feature. Some users just aren't using the code that a bug affects, just as some users won't care about a particular new feature. Thus out of your choices, I like choice 3 the best.

Another modification is you could omit the `.0` minor number _unless_ there is a bugfix, in which case you bump it to `.1` and so on. Gradle does this with `v3.1`, `v3.2`, and `v3.2.1` for a bugfix. Firefox does this too with security patches, e.g. `48.0.1`.

I don't really like gnome-style odd/even versioning, because it's usually not obvious a project works that way.

One system I like is https://mvnrepository.com/artifact/com.lihaoyi/ammonite-repl_2.11.7 , whose CI system just publishes things on master by commit hash apparently. If there's a bugfix or feature in master that somebody wants to use immediately, they can just pluck out the specific commit. Otherwise they can just wait till the next "official" release and get the batch of new features with a stamp of stability. You can do the same thing with explicitly referencing SNAPSHOT builds by their timestamp, but I personally like that less, since you then can't see the exact source code that got built into the snapshot.

**Comment by jentfoo** [comment]
> This looks like a fun bikeshed.

I thought you might enjoy it, haha.  Thanks for responding, I knew you would have some great insights into this.

> What's bad about incrementing the middle number like crazy?

Several things, none of which are technical issues.  As far as effort, a patch version is only slightly easier than a minor release (only things omitted are javadoc updates, and wiki updates).  So if we go to a two version number, those extra efforts are not significant enough to be concerned about.

The issues I have are mostly OCD related.  For example what's the point in having a `.0` in every version?  Patches are very rare these days, and the recent patch versions (with only one or two exceptions) have been a bit of a stretch or gray area if they should have even been a patch version.  It seems like wasted information, not really providing any value if it's almost always a `.0`.

> Another modification is you could omit the .0 minor number unless there is a bugfix

This is actually a really good idea I had not considered (even though I have seen it before).  I am inclined to go down to two numbers with the idea that if we ever had a very trivial fix, with nothing else waiting we could just add a `.1` to the end.

**Comment by blendmaster** [comment]
>This is actually a really good idea I had not considered (even though I have seen it before). I am inclined to go down to two numbers with the idea that if we ever had a very trivial fix, with nothing else waiting we could just add a .1 to the end.

There's a chance some java/maven tool chokes on the sometimes missing minor version in an annoying way, but otherwise leaving it out and going with 5.0, 5.1, etc seems extremely tolerable.

**Comment by blendmaster** [comment]
There's also openssl's versioning scheme https://www.openssl.org/docs/faq.html#MISC8 if you want to dip into `5.0a`, `5.0b` and so on.

**Comment by jentfoo** [comment]
Going ahead and going to two numbers, `5.0-SNAPSHOT` how now been released with this new versioning.  If anyone has any further comments feel free to make them here (or open a new issue)
