### ISSUE TITLE
[Feature request] Make ExecutorLimiter support TaskPriority with PriorityScheduler as Executor

### ISSUE THREAD

**Issue by jiming** [threadly/threadly#219]
Hi @jentfoo 

Is it possible to let ExecutorLimiter, SubmitterSchedulerLimiter, and SchedulerServiceLimiter support TaskPriority with PriorityScheduler as Executor.

```
public ExecutorLimiter(PriorityScheduler executor, TaskPriority pr, int maxConcurrency)
```

Or else, any trick to do the same thing?

Thanks!

**Comment by jentfoo** [comment]
I am not sure exactly what you are asking.  I could see two possible things you are asking for:

* A Limiter implementation that allows you to submit task priorities with each task.  We actually used to have this and then later removed it.  The problem was basically the priority kind of lost its meaning after being limited by the limiter and then needing to delegate to the lower pool.  Thinking about this again I do think a different variant of this could make sense where the limiter considers priority only within itself and then when it submits the task to the parent pool it would always use high priority.  However I am unsure if that is intuitive to others?  And the LOE would be higher than the other limiters.

* If you want a limiter that is applying a specific priority to each task as it provides them to the parent pool, this is something which is already possible.  You can wrap a `PriorityScheduler` so that the default priority for tasks is different from what it was constructed with.  That way you can pass this wrapped scheduler into classes / use cases that may only accept `Executor` or other non-priority aware code, but then have them submitting tasks of a given priority (hopefully that makes sense).

Take a look at the javadocs here: http://threadly.github.io/threadly/javadocs/5.3/org/threadly/concurrent/wrapper/PrioritySchedulerDefaultPriorityWrapper.html

Let me know if you have any questions or further thoughts (particularly if you have documentation suggestions).

**Comment by jiming** [comment]
Hi @jentfoo:

What I wanted is a combination of Limiter and PrioritySchedulerDefaultPriorityWrapper. There might have multiple limiter share the same parent PriorityScheduler. I expected each limiter has its fixed priority. And the task from limiter with higher priority should have higher priority to win a new thread if the PriorityScheduler pool is exhausted.

Thanks!

**Comment by jentfoo** [comment]
Sorry for the delay in my response.

> I expected each limiter has its fixed priority. And the task from limiter with higher priority should have higher priority to win a new thread if the 

This still seems possible to me right now with existing threadly tools.  Let's say you wanted a several limiters of different priorities, each individual priority limited to 10 tasks.  This would look like:
```
Executor lowPriority = new ExecutorLimiter(new PrioritySchedulerDefaultPriorityWrapper(delegateScheduler, TaskPriority.Low), 10);
Executor highPriority = new ExecutorLimiter(new PrioritySchedulerDefaultPriorityWrapper(delegateScheduler, TaskPriority.High), 10);
...
```

Does that kind of match what you are asking for?

**Comment by jentfoo** [comment]
Going to go ahead and close this.  If the above does not satisfy your needs please comment and I will make sure we have support for what you need.

**Comment by jiming** [comment]
Great thanks, dude. I will check later for sure!
