### ISSUE TITLE
[Improvement]TaskPriority add more level

### ISSUE THREAD

**Issue by jiming** [threadly/threadly#220]
Hi @jentfoo ,

TaskPriority current has only two level (I didn't count Starvable, it is for special purpose). 

I think maybe five level should be supplied, what do you say?

Have a nice day!

Jiming

**Comment by jentfoo** [comment]
There is memory and code complexity issues with having more task priorities.  The biggest issue I would have is how our logic for polling tasks would get larger / use more of the CPU cache.  So I think the performance losses would likely not make it worth it.

I also think it might be hard to communicate the behavior between more granular priorities.  Right now each one has a behavior characteristic that is fairly easy to describe.

I am going to close this because I have considered it and just don't think it's very realistically useful to others considering the complexity, but if you have some brilliant ideas on how to do it feel free to keep commenting!  (can always reopen)

**Comment by jiming** [comment]
> The biggest issue I would have is how our logic for polling tasks would get larger / use more of the CPU cache. 

IMHO, TaskPriority is used to order the tasks in the task queue, not for take more CPU. If threadly is not for mobile phone, I think the resources(CPU cache) take with more prirorities is not a big deal for modern server.

Perhaps 5 level is a little more, however 3 level is quite reasonable number.
- HIGH: should be executed immediately
- MEDIUM: general purpose tasks
- LOW: can be delayed a little from time to time
- Starving: 

Thanks!
