### ISSUE TITLE
Unfair threadexecutor is slower than executorservice (new FixedThreadPool)

### ISSUE THREAD

**Issue by replydev** [threadly/threadly#267]
I made a java program that scan ip ranges, threadly unfair executorservice is significantly slower than java 8 executor service.

**Comment by jentfoo** [comment]
This is not too surprising.  `UnfairExecutorService` can be quite challenging to get peak performance from, so much so that I have considered removing it.  In order for it to have an advantage it needs:
* Very uniform task execution times
* Very well distributed tasks, we have a couple algorithms that help, but...
* Ideally the thread submitting the task will submit to the same shard it's currently executing on

I personally have stopped using UnfairExecutor, instead building designs that reduce the churn through the executor (ie make tasks bigger so the executor does less work).  I considered removing it, but would like something to replace it first.  I would like to have some tooling to help take a series of small tasks and help execute them to avoid the pool overheads.  Perhaps some future improvements to UnfairExecutor or maybe something different entirely.  There is lots of room for improving the cross-thread communications that are necessary in handing off a task in an execution pool.  If you have any feedback on if it should be removed, or other design ideas, we would love to hear them.

It's worth noting that the performance of java's `ThreadPoolExecutor` is quite good, and should be considered for use, even when otherwise using threadly. `ScheduledThreadPoolExecutor` on the other hand makes fairly notable performance compromises.

Personally I use `PriorityScheduler` most of the time.  It has execution performance similar to `ThreadPoolExecutor` but provides scheduling capabilities, priority capabilities, and some improved ergonomic and guarantees in some cases.

Let me know if that helps or what additional questions you might have.

**Comment by replydev** [comment]
Thanks a lot for your reply! My goal is too make the fastest possible async multithreading system, no matter the order of execution, my program does the same task million times, feel free to check your self (https://github.com/replydev/Quboscanner), and as now Java 8 executor service is the fastest solution. What do you advice to optimize the multithreading system? I'm learning these java aspects and i'm not much professional, sorry about this.

**Comment by jentfoo** [comment]
I took a look at your project and don't believe the thread pool is your primary bottleneck.  A few thoughts from my perspective:
* Generally your bottleneck is the timeout for the network communications, so you will want a lot of thread
* I am not sure if your logic for limiting the concurrency is right.  I see you tracking `currentThreads` but I don't see you ever decrementing it, nor do I see you blocking when you're at capacity.  It seems once you're at capacity you are just skip the check.

I would instead of creating a pool every time (or worse new Threads), I would just create a single pool which makes sense and reuse it to avoid thread churn.  I would size this pool fairly large because you're more bottlenecked on your timeout than anything.  I would even consider 1k or 2k threads (recognizing memory as what we're willing to give up in the sake of speed).

If using a single pool I would instead do a `.submit` with a future to be able to know when all checks have completed.  Using a ListenableFuture you can easily get a push notification when a hit is found too.

As for the pool of choice, I see no problems with java's `ThreadPoolExecutor` for your current use.  If you wanted to schedule tasks then `PriorityScheduler` could be a good choice.  `PriorityScheduler` may be a good choice if you do want to make use of `ListenableFuture`.

If you really want to squeeze the most out of your performance, I would put things in JMH.  `Check` would in particular be a good class to test under JMH.  I think there could be some potential GC and other overheads worth considering there more than the pool is likely impacting you.

Let me know if you have any further questions

**Comment by replydev** [comment]
Thank you for your help, i don't understood when you said: "creating new pool every time". In fact the thread pool, the fixedThreadPool, is initialized one time, and after i constantly add runnable tasks. The atomic integer that stores current running threads is decremented in check runnable class
![immagine](https://user-images.githubusercontent.com/43727434/77313936-06870f00-6d05-11ea-96e4-c3926cb3f42b.png). I will try to use a listenable future. We already run the program with thousand of threads, but after 11k the jvm gives an out of memory error even if the server ram is at 40% or less. After that crashes.

**Comment by jentfoo** [comment]
Feel free to email me directly if you want more help: jent@threadly.org
