### ISSUE TITLE
A problem of source code learning

### ISSUE THREAD

**Issue by ZPZP1** [threadly/threadly#283]
Why does the ListenerHelper use a collection that is not thread-safe, and is it written in this way that the current thread is working on the collection somewhere else at the same time?
`
boolean addingFromCallingThread = Thread.holdsLock(listenersLock);
    synchronized (listenersLock) {
      if (executor == null) {
        if (addingFromCallingThread && inThreadListeners != null) {
`

**Comment by jentfoo** [comment]
Thank you for the question.  The TL:DR; is that ListenerHelper is highly optimized.

One of the key considerations of our library is that if `ListenableFuture` (or more specifically [ListenableFutureTask](https://github.com/threadly/threadly/blob/master/src/main/java/org/threadly/concurrent/future/ListenableFutureTask.java)) is to replace java's built in FutureTask, we need to carefully consider and minimize any additional performance impacts that may occur with ListenableFutureTask.

Because thread pools may contain VERY large quantities of tasks, the memory overheads added by each task is a very important consideration.  And with ListenerHelper it provides the key logic for how listeners are registered and executed on the Futures.

For that reason we have fairly complicated logic which has evolved over the years.  The implementation for storing the listeners will vary depending on the state.  Starting with `null` then `Collections.singletonList`, and finally `ArrayList`: https://github.com/threadly/threadly/blob/master/src/main/java/org/threadly/concurrent/event/ListenerHelper.java#L144-L153

Switching to a concurrent structure would make this much simpler, however it would notably increase the memory overheads.

Overall Threadly has undergone extensive performance testing on a variety of hardware and jdk versions.  We generally accept taking on additional complexity if there is measurable performance gains to be had.  At this point this library has been used extensively for years in a wide range of applications and use cases.  So I do feel confident in the correctness of our implementation.

Let me know if you have any additional questions, thank you!
